# Generated by Django 5.1.4 on 2024-12-31 11:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('SHOE_REVENUE', 'Shoe Shop Revenue'), ('BARBER_ADULT', 'Barber Adult Haircut'), ('BARBER_CHILD', 'Barber Child Haircut'), ('BARBER_FREE', 'Barber Free Haircut'), ('MEATBALL_SALES', 'Meatball Sales'), ('MEATBALL_SALAD', 'Meatball Salad Cost')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'entry_type'],
                'indexes': [models.Index(fields=['date', 'entry_type'], name='core_dailye_date_d8ed1d_idx')],
                'unique_together': {('date', 'entry_type')},
            },
        ),
    ]
