# Generated by Django 5.1.4 on 2024-12-31 12:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyentry',
            options={'ordering': ['-date', 'entry_type'], 'verbose_name': 'Daily Entry', 'verbose_name_plural': 'Daily Entries'},
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='entry_type',
            field=models.CharField(choices=[('SHOE_REVENUE', 'Shoe Shop Revenue'), ('BARBER_ADULT', 'Barber Adult Haircut'), ('BARBER_CHILD', 'Barber Child Haircut'), ('BARBER_FREE', 'Barber Free Haircut'), ('MEATBALL_SALES', 'Meatball Sales'), ('MEATBALL_SALAD', 'Meatball Salad Cost')], max_length=20, verbose_name='Entry Type'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Value'),
        ),
    ]
